"""Closed operation labels and byte-exact recovery of pre-diagnostic audit records."""

from datetime import UTC, datetime
from uuid import UUID, uuid4

import pytest
from pydantic import ValidationError

from zacai.ingestion.artifact_store import canonical_bytes
from zacai.intelligence.review_audit import (
    ContextualAuditEvent,
    ContextualAuditStage,
    ContextualFailureStep,
)


def legacy_data():
    return {
        "format": "zac-contextual-run-audit-v1",
        "audit_event_id": str(UUID(int=1)), "run_id": str(UUID(int=2)),
        "task_id": str(UUID(int=3)), "builder_id": str(UUID(int=4)),
        "recorded_at": datetime(2026, 10, 5, tzinfo=UTC).isoformat().replace("+00:00", "Z"),
        "trust_boundary": "BRAINSTORM", "data_classification": "CONFIDENTIAL",
        "stage": "RUN_FAILED", "request_digest": "a" * 64,
        "context_digest": "b" * 64, "model_digest": "c" * 64,
        "route": {"provider_id": "invented", "model_id": "fixture", "runtime_id": "test"},
        "packet_source_id": None, "packet_digest": None,
    }


def test_prior_failure_audit_round_trips_byte_exactly():
    data = legacy_data()
    event = ContextualAuditEvent.model_validate(data)
    assert event.failure_step is None
    assert canonical_bytes(event.model_dump(mode="json")) == canonical_bytes(data)
    assert "failure_step" not in event.model_dump()
    assert "failure_step" not in event.model_dump_json()


@pytest.mark.parametrize("step", list(ContextualFailureStep))
def test_closed_failure_operation_round_trips(step):
    before = {ContextualFailureStep.REQUEST_AUDIT, ContextualFailureStep.CLAIM,
              ContextualFailureStep.RUNTIME_PREFLIGHT, ContextualFailureStep.DISPATCH_AUDIT,
              ContextualFailureStep.DISPATCH_CLOCK_START}
    after = {ContextualFailureStep.CAPTURE_SESSION_CLOSE, ContextualFailureStep.PROTECTION, ContextualFailureStep.RECOVERY_RECEIPT_VALIDATION,
             ContextualFailureStep.PACKET_READ, ContextualFailureStep.PACKET_VALIDATION,
             ContextualFailureStep.METADATA_ACCESS_CHECK, ContextualFailureStep.RELEASE_LATENCY_CHECK}
    data = legacy_data() | {"failure_step": step.value, "dispatch_attempted": step not in before}
    if step in after:
        data.update(packet_source_id=str(UUID(int=5)), packet_digest="d" * 64)
    event = ContextualAuditEvent.model_validate(data)
    assert event.failure_step == step
    assert canonical_bytes(event.model_dump(mode="json")) == canonical_bytes(data)


@pytest.mark.parametrize("stage", [ContextualAuditStage.REQUEST_PREPARED,
                                     ContextualAuditStage.DISPATCH_PREPARED,
                                     ContextualAuditStage.PACKET_CAPTURED])
def test_nonfailure_cannot_assert_failure_operation(stage):
    data = legacy_data() | {"stage": stage.value, "failure_step": "GENERATION", "dispatch_attempted": True}
    if stage == ContextualAuditStage.PACKET_CAPTURED:
        data.update(packet_source_id=str(uuid4()), packet_digest="d" * 64)
    with pytest.raises(ValidationError):
        ContextualAuditEvent.model_validate(data)


def test_private_free_text_cannot_enter_failure_operation():
    with pytest.raises(ValidationError):
        ContextualAuditEvent.model_validate(legacy_data() | {"failure_step": "PRIVATE response text"})


# Golden bytes generated by the pre-change audit writer at 896b758, invented IDs only.
LEGACY_GOLDENS = {
    'REQUEST_PREPARED': (b'{"audit_event_id":"00000000-0000-0000-0000-000000000001","builder_id":"00000000-0000-0000-0000-000000000004","context_digest":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","data_classification":"CONFIDENTIAL","format":"zac-contextual-run-audit-v1","model_digest":"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","packet_digest":null,"packet_source_id":null,"recorded_at":"2026-10-05T00:00:00Z","request_digest":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","route":{"model_id":"fixture","provider_id":"invented","runtime_id":"test"},"run_id":"00000000-0000-0000-0000-000000000002","stage":"REQUEST_PREPARED","task_id":"00000000-0000-0000-0000-000000000003","trust_boundary":"BRAINSTORM"}', 'c3c11d62b23be3449292a21c6b3321d008f50a48c565ff9af387dbf5f5403544'),
    'DISPATCH_PREPARED': (b'{"audit_event_id":"00000000-0000-0000-0000-000000000001","builder_id":"00000000-0000-0000-0000-000000000004","context_digest":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","data_classification":"CONFIDENTIAL","format":"zac-contextual-run-audit-v1","model_digest":"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","packet_digest":null,"packet_source_id":null,"recorded_at":"2026-10-05T00:00:00Z","request_digest":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","route":{"model_id":"fixture","provider_id":"invented","runtime_id":"test"},"run_id":"00000000-0000-0000-0000-000000000002","stage":"DISPATCH_PREPARED","task_id":"00000000-0000-0000-0000-000000000003","trust_boundary":"BRAINSTORM"}', 'eca98c4060393938effe65fe15851a3579620fab838dca22faa923602ce6f53c'),
    'PACKET_CAPTURED': (b'{"audit_event_id":"00000000-0000-0000-0000-000000000001","builder_id":"00000000-0000-0000-0000-000000000004","context_digest":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","data_classification":"CONFIDENTIAL","format":"zac-contextual-run-audit-v1","model_digest":"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","packet_digest":"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd","packet_source_id":"00000000-0000-0000-0000-000000000005","recorded_at":"2026-10-05T00:00:00Z","request_digest":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","route":{"model_id":"fixture","provider_id":"invented","runtime_id":"test"},"run_id":"00000000-0000-0000-0000-000000000002","stage":"PACKET_CAPTURED","task_id":"00000000-0000-0000-0000-000000000003","trust_boundary":"BRAINSTORM"}', '2024dc978153a3723f0d7e81f9c97f7dd32c7a1bafcd9189c245cd2a0116c805'),
    'RUN_FAILED': (b'{"audit_event_id":"00000000-0000-0000-0000-000000000001","builder_id":"00000000-0000-0000-0000-000000000004","context_digest":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","data_classification":"CONFIDENTIAL","format":"zac-contextual-run-audit-v1","model_digest":"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","packet_digest":null,"packet_source_id":null,"recorded_at":"2026-10-05T00:00:00Z","request_digest":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","route":{"model_id":"fixture","provider_id":"invented","runtime_id":"test"},"run_id":"00000000-0000-0000-0000-000000000002","stage":"RUN_FAILED","task_id":"00000000-0000-0000-0000-000000000003","trust_boundary":"BRAINSTORM"}', '09ddc6b1463343aa83842fb130cef1afed606c76a35a7edae45d8542dae64af6'),
    "POST_CAPTURE_RUN_FAILED": (b'{"audit_event_id":"00000000-0000-0000-0000-000000000001","builder_id":"00000000-0000-0000-0000-000000000004","context_digest":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","data_classification":"CONFIDENTIAL","format":"zac-contextual-run-audit-v1","model_digest":"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","packet_digest":"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd","packet_source_id":"00000000-0000-0000-0000-000000000005","recorded_at":"2026-10-05T00:00:00Z","request_digest":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","route":{"model_id":"fixture","provider_id":"invented","runtime_id":"test"},"run_id":"00000000-0000-0000-0000-000000000002","stage":"RUN_FAILED","task_id":"00000000-0000-0000-0000-000000000003","trust_boundary":"BRAINSTORM"}', 'ccf07a069c1a53475161a0853bff6d4f2c782eb66706c62aceaf65d548232af0'),
}


@pytest.mark.parametrize("raw,expected_hash", list(LEGACY_GOLDENS.values()))
def test_prechange_writer_golden_bytes_and_hashes(raw, expected_hash):
    from zacai.ingestion.artifact_store import content_hash_of

    event = ContextualAuditEvent.model_validate_json(raw)
    encoded = canonical_bytes(event.model_dump(mode="json"))
    assert encoded == raw
    assert content_hash_of(encoded) == expected_hash


@pytest.mark.parametrize("step", [ContextualFailureStep.PROTECTION,
                                     ContextualFailureStep.PACKET_READ,
                                     ContextualFailureStep.METADATA_ACCESS_CHECK])
def test_postcapture_failure_retains_packet_binding(step):
    data = legacy_data() | {"failure_step": step.value, "dispatch_attempted": True,
                            "packet_source_id": str(UUID(int=5)), "packet_digest": "d" * 64}
    event = ContextualAuditEvent.model_validate(data)
    assert canonical_bytes(event.model_dump(mode="json")) == canonical_bytes(data)


def test_explicit_null_is_not_canonical_legacy_encoding():
    data = legacy_data() | {"failure_step": None}
    with pytest.raises(ValidationError):
        ContextualAuditEvent.model_validate(data)


@pytest.mark.parametrize("changes", [
    {"failure_step": "GENERATION"}, {"dispatch_attempted": True},
    {"failure_step": "GENERATION", "dispatch_attempted": 1},
    {"failure_step": "GENERATION", "dispatch_attempted": False},
    {"failure_step": "CLAIM", "dispatch_attempted": True},
    {"failure_step": "PROTECTION", "dispatch_attempted": True},
    {"failure_step": "GENERATION", "dispatch_attempted": True,
     "packet_source_id": str(UUID(int=5)), "packet_digest": "d" * 64},
    {"failure_step": "AUTHORIZATION_RECHECK", "dispatch_attempted": False,
     "packet_source_id": str(UUID(int=5)), "packet_digest": "d" * 64},
])
def test_impossible_diagnostic_shapes_rejected(changes):
    with pytest.raises(ValidationError):
        ContextualAuditEvent.model_validate(legacy_data() | changes)
