"""initial_state_schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-19 22:41:31.018146

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitment_head',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='commitment_head_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('entity_id', 'trust_boundary', name='uq_commitment_head_entity_boundary')
    )
    op.create_table('person_head',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='person_head_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('entity_id', 'trust_boundary', name='uq_person_head_entity_boundary')
    )
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='source_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('data_classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'HIGHLY_RESTRICTED', name='source_data_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('system', sa.Enum('EMAIL', 'SLACK', 'FIREFLIES', 'SALESFORCE', 'CLICKUP', 'DRIVE', 'USER_INSTRUCTION', 'MANUAL', name='source_system', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'trust_boundary', name='uq_source_id_boundary')
    )
    op.create_table('commitment',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='commitment_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('data_classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'HIGHLY_RESTRICTED', name='commitment_data_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DONE', 'CANCELLED', 'RETRACTED', name='commitment_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('owner_person_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id', 'trust_boundary'], ['commitment_head.entity_id', 'commitment_head.trust_boundary'], name='fk_commitment_head_boundary'),
    sa.ForeignKeyConstraint(['owner_person_id', 'trust_boundary'], ['person_head.entity_id', 'person_head.trust_boundary'], name='fk_commitment_owner_boundary'),
    sa.PrimaryKeyConstraint('entity_id', 'version'),
    sa.UniqueConstraint('entity_id', 'version', 'trust_boundary', name='uq_commitment_entity_version_boundary')
    )
    op.create_table('person',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='person_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('data_classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'HIGHLY_RESTRICTED', name='person_data_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RETRACTED', name='person_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('primary_email', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id', 'trust_boundary'], ['person_head.entity_id', 'person_head.trust_boundary'], name='fk_person_head_boundary'),
    sa.PrimaryKeyConstraint('entity_id', 'version'),
    sa.UniqueConstraint('entity_id', 'version', 'trust_boundary', name='uq_person_entity_version_boundary')
    )
    op.create_table('commitment_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commitment_entity_id', sa.UUID(), nullable=False),
    sa.Column('commitment_version', sa.Integer(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='commitment_evidence_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('stance', sa.Enum('SUPPORTS', 'CONTRADICTS', name='commitment_evidence_stance', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('noted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_commitment_evidence_confidence_range'),
    sa.ForeignKeyConstraint(['commitment_entity_id', 'commitment_version', 'trust_boundary'], ['commitment.entity_id', 'commitment.version', 'commitment.trust_boundary'], name='fk_commitment_evidence_commitment'),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_commitment_evidence_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_entity_id', sa.UUID(), nullable=False),
    sa.Column('person_version', sa.Integer(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='person_evidence_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('stance', sa.Enum('SUPPORTS', 'CONTRADICTS', name='person_evidence_stance', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('noted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_person_evidence_confidence_range'),
    sa.ForeignKeyConstraint(['person_entity_id', 'person_version', 'trust_boundary'], ['person.entity_id', 'person.version', 'person.trust_boundary'], name='fk_person_evidence_person'),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_person_evidence_source'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- D026: append-only enforcement -------------------------------------
    # person_head/commitment_head are the one deliberate, named exception -
    # every other table here is insert-only, enforced by the database
    # itself (a trigger fires regardless of who owns the table, unlike a
    # GRANT/REVOKE, which a table owner always bypasses), not by
    # application convention alone.
    op.execute(
        """
        CREATE FUNCTION zacai_forbid_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only; % is not permitted', TG_TABLE_NAME, TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table_name in ("source", "person", "commitment", "person_evidence", "commitment_evidence"):
        op.execute(
            f"""
            CREATE TRIGGER {table_name}_forbid_mutation
            BEFORE UPDATE OR DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION zacai_forbid_mutation();
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table_name in ("source", "person", "commitment", "person_evidence", "commitment_evidence"):
        op.execute(f"DROP TRIGGER IF EXISTS {table_name}_forbid_mutation ON {table_name};")
    op.execute("DROP FUNCTION IF EXISTS zacai_forbid_mutation();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_evidence')
    op.drop_table('commitment_evidence')
    op.drop_table('person')
    op.drop_table('commitment')
    op.drop_table('source')
    op.drop_table('person_head')
    op.drop_table('commitment_head')
    # ### end Alembic commands ###
