"""entity_model_expansion

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-21 11:21:31.291508

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_head',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='company_head_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('entity_id', 'trust_boundary', name='uq_company_head_entity_boundary')
    )
    op.create_table('project_head',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='project_head_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('entity_id', 'trust_boundary', name='uq_project_head_entity_boundary')
    )
    op.create_table('company',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='company_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('data_classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'HIGHLY_RESTRICTED', name='company_data_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RETRACTED', name='company_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('relationship_kind', sa.Enum('CLIENT', 'PROSPECT', 'PARTNER', 'INTERNAL', name='company_relationship_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id', 'trust_boundary'], ['company_head.entity_id', 'company_head.trust_boundary'], name='fk_company_head_boundary'),
    sa.PrimaryKeyConstraint('entity_id', 'version'),
    sa.UniqueConstraint('entity_id', 'version', 'trust_boundary', name='uq_company_entity_version_boundary')
    )
    op.create_table('meeting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='meeting_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('data_classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'HIGHLY_RESTRICTED', name='meeting_data_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('noted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'trust_boundary'], ['project_head.entity_id', 'project_head.trust_boundary'], name='fk_meeting_project_boundary'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'trust_boundary', name='uq_meeting_id_boundary')
    )
    op.create_table('person_company_relationship',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='person_company_relationship_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('data_classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'HIGHLY_RESTRICTED', name='person_company_relationship_data_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('relationship_kind', sa.Enum('EMPLOYEE', 'CONTACT', 'OTHER', name='person_company_relationship_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('noted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'trust_boundary'], ['company_head.entity_id', 'company_head.trust_boundary'], name='fk_person_company_relationship_company'),
    sa.ForeignKeyConstraint(['person_id', 'trust_boundary'], ['person_head.entity_id', 'person_head.trust_boundary'], name='fk_person_company_relationship_person'),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_person_company_relationship_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='project_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('data_classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'HIGHLY_RESTRICTED', name='project_data_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETE', 'RETRACTED', name='project_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'trust_boundary'], ['company_head.entity_id', 'company_head.trust_boundary'], name='fk_project_company_boundary'),
    sa.ForeignKeyConstraint(['entity_id', 'trust_boundary'], ['project_head.entity_id', 'project_head.trust_boundary'], name='fk_project_head_boundary'),
    sa.PrimaryKeyConstraint('entity_id', 'version'),
    sa.UniqueConstraint('entity_id', 'version', 'trust_boundary', name='uq_project_entity_version_boundary')
    )
    op.create_table('company_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_entity_id', sa.UUID(), nullable=False),
    sa.Column('company_version', sa.Integer(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='company_evidence_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('stance', sa.Enum('SUPPORTS', 'CONTRADICTS', name='company_evidence_stance', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('noted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_company_evidence_confidence_range'),
    sa.ForeignKeyConstraint(['company_entity_id', 'company_version', 'trust_boundary'], ['company.entity_id', 'company.version', 'company.trust_boundary'], name='fk_company_evidence_company'),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_company_evidence_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='decision_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('data_classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'HIGHLY_RESTRICTED', name='decision_data_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('supersedes_decision_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id', 'trust_boundary'], ['meeting.id', 'meeting.trust_boundary'], name='fk_decision_meeting_boundary'),
    sa.ForeignKeyConstraint(['project_id', 'trust_boundary'], ['project_head.entity_id', 'project_head.trust_boundary'], name='fk_decision_project_boundary'),
    sa.ForeignKeyConstraint(['supersedes_decision_id', 'trust_boundary'], ['decision.id', 'decision.trust_boundary'], name='fk_decision_supersedes_boundary', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'trust_boundary', name='uq_decision_id_boundary')
    )
    op.create_table('meeting_attendee',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='meeting_attendee_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id', 'trust_boundary'], ['meeting.id', 'meeting.trust_boundary'], name='fk_meeting_attendee_meeting'),
    sa.ForeignKeyConstraint(['person_id', 'trust_boundary'], ['person_head.entity_id', 'person_head.trust_boundary'], name='fk_meeting_attendee_person'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_retraction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='meeting_retraction_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('retracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id', 'trust_boundary'], ['meeting.id', 'meeting.trust_boundary'], name='fk_meeting_retraction_meeting'),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_meeting_retraction_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', name='uq_meeting_retraction_meeting_id')
    )
    op.create_table('meeting_source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='meeting_source_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_role', sa.Enum('CALENDAR_EVENT', 'TRANSCRIPT', 'SUMMARY', 'RECORDING', 'NOTES', 'FOLLOW_UP', name='meeting_source_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('noted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id', 'trust_boundary'], ['meeting.id', 'meeting.trust_boundary'], name='fk_meeting_source_meeting'),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_meeting_source_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_entity_id', sa.UUID(), nullable=False),
    sa.Column('project_version', sa.Integer(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='project_evidence_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('stance', sa.Enum('SUPPORTS', 'CONTRADICTS', name='project_evidence_stance', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('noted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_project_evidence_confidence_range'),
    sa.ForeignKeyConstraint(['project_entity_id', 'project_version', 'trust_boundary'], ['project.entity_id', 'project.version', 'project.trust_boundary'], name='fk_project_evidence_project'),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_project_evidence_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='decision_evidence_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('stance', sa.Enum('SUPPORTS', 'CONTRADICTS', name='decision_evidence_stance', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('noted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_decision_evidence_confidence_range'),
    sa.ForeignKeyConstraint(['decision_id', 'trust_boundary'], ['decision.id', 'decision.trust_boundary'], name='fk_decision_evidence_decision'),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_decision_evidence_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_retraction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='decision_retraction_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('retracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id', 'trust_boundary'], ['decision.id', 'decision.trust_boundary'], name='fk_decision_retraction_decision'),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_decision_retraction_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', name='uq_decision_retraction_decision_id')
    )
    op.add_column('commitment', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_commitment_project_boundary', 'commitment', 'project_head', ['project_id', 'trust_boundary'], ['entity_id', 'trust_boundary'])
    # ### end Alembic commands ###

    # --- D029: append-only enforcement --------------------------------------
    # Reuses the zacai_forbid_mutation() trigger function created by 0001 -
    # not recreated here. company_head/project_head are the (D026-established)
    # exception: mutable-by-design pointers, no trigger. Every other new
    # table - versioned content, typed links, and the two retraction tables -
    # is append-only, exactly like source/person/commitment/*_evidence.
    for table_name in (
        "company",
        "company_evidence",
        "project",
        "project_evidence",
        "person_company_relationship",
        "meeting",
        "meeting_source",
        "meeting_attendee",
        "decision",
        "decision_evidence",
        "decision_retraction",
        "meeting_retraction",
    ):
        op.execute(
            f"""
            CREATE TRIGGER {table_name}_forbid_mutation
            BEFORE UPDATE OR DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION zacai_forbid_mutation();
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table_name in (
        "company",
        "company_evidence",
        "project",
        "project_evidence",
        "person_company_relationship",
        "meeting",
        "meeting_source",
        "meeting_attendee",
        "decision",
        "decision_evidence",
        "decision_retraction",
        "meeting_retraction",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS {table_name}_forbid_mutation ON {table_name};")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_commitment_project_boundary', 'commitment', type_='foreignkey')
    op.drop_column('commitment', 'project_id')
    op.drop_table('decision_retraction')
    op.drop_table('decision_evidence')
    op.drop_table('project_evidence')
    op.drop_table('meeting_source')
    op.drop_table('meeting_retraction')
    op.drop_table('meeting_attendee')
    op.drop_table('decision')
    op.drop_table('company_evidence')
    op.drop_table('project')
    op.drop_table('person_company_relationship')
    op.drop_table('meeting')
    op.drop_table('company')
    op.drop_table('project_head')
    op.drop_table('company_head')
    # ### end Alembic commands ###
