"""ingestion_architecture

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-21 16:22:54.781920

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: str | Sequence[str] | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_cursor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector', sa.Text(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='ingestion_cursor_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('cursor_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector', 'trust_boundary', name='uq_ingestion_cursor_connector_boundary')
    )
    op.create_table('ingestion_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector', sa.Text(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='ingestion_run_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'SUCCEEDED', 'FAILED', name='ingestion_run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_fetched', sa.Integer(), nullable=True),
    sa.Column('items_ingested', sa.Integer(), nullable=True),
    sa.Column('items_skipped', sa.Integer(), nullable=True),
    sa.Column('items_failed', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='extraction_record_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUCCEEDED', 'FAILED', name='extraction_record_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_extraction_record_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'trust_boundary', name='uq_extraction_record_id_boundary')
    )
    op.create_table('source_classification_elevation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='source_classification_elevation_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('previous_classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'HIGHLY_RESTRICTED', name='source_classification_elevation_previous', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('new_classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'HIGHLY_RESTRICTED', name='source_classification_elevation_new', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('elevated_by', sa.Text(), nullable=False),
    sa.Column('elevated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_source_classification_elevation_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_candidate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='extraction_candidate_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('extraction_record_id', sa.UUID(), nullable=False),
    sa.Column('candidate_type', sa.Enum('DECISION', 'COMMITMENT', name='extraction_candidate_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_person_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('proposed_classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'HIGHLY_RESTRICTED', name='extraction_candidate_proposed_classification', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_extraction_candidate_confidence_range'),
    sa.ForeignKeyConstraint(['extraction_record_id', 'trust_boundary'], ['extraction_record.id', 'extraction_record.trust_boundary'], name='fk_extraction_candidate_record'),
    sa.ForeignKeyConstraint(['meeting_id', 'trust_boundary'], ['meeting.id', 'meeting.trust_boundary'], name='fk_extraction_candidate_meeting'),
    sa.ForeignKeyConstraint(['project_id', 'trust_boundary'], ['project_head.entity_id', 'project_head.trust_boundary'], name='fk_extraction_candidate_project'),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_extraction_candidate_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'trust_boundary', name='uq_extraction_candidate_id_boundary')
    )
    op.create_table('unresolved_identity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='unresolved_identity_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('raw_name', sa.Text(), nullable=True),
    sa.Column('raw_email', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('noted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id', 'trust_boundary'], ['meeting.id', 'meeting.trust_boundary'], name='fk_unresolved_identity_meeting'),
    sa.ForeignKeyConstraint(['source_id', 'trust_boundary'], ['source.id', 'source.trust_boundary'], name='fk_unresolved_identity_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_candidate_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='extraction_candidate_review_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('outcome', sa.Enum('APPROVED', 'REJECTED', name='extraction_candidate_review_outcome', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('promoted_entity_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id', 'trust_boundary'], ['extraction_candidate.id', 'extraction_candidate.trust_boundary'], name='fk_extraction_candidate_review_candidate'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', name='uq_extraction_candidate_review_candidate_id')
    )
    op.add_column('source', sa.Column('content_hash', sa.Text(), nullable=True))
    op.add_column('source', sa.Column('content_location', sa.Text(), nullable=True))
    op.add_column('source', sa.Column('supersedes_source_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_source_system_external_ref_hash_boundary', 'source', ['system', 'external_ref', 'trust_boundary', 'content_hash'])
    op.create_foreign_key('fk_source_supersedes_boundary', 'source', 'source', ['supersedes_source_id', 'trust_boundary'], ['id', 'trust_boundary'], initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###

    # --- D030: append-only enforcement --------------------------------------
    # Reuses the zacai_forbid_mutation() trigger function created by 0001 -
    # not recreated here. `ingestion_cursor`/`ingestion_run` are the
    # deliberate mutable exceptions (D030): pure operational bookkeeping,
    # not content-bearing facts, joining `person_head`/`commitment_head`/
    # `company_head`/`project_head` (D026/D029). `source` itself already
    # carries its append-only trigger from 0001 - its new nullable columns
    # here need no trigger change. Every other new table is append-only.
    for table_name in (
        "extraction_record",
        "extraction_candidate",
        "extraction_candidate_review",
        "source_classification_elevation",
        "unresolved_identity",
    ):
        op.execute(
            f"""
            CREATE TRIGGER {table_name}_forbid_mutation
            BEFORE UPDATE OR DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION zacai_forbid_mutation();
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table_name in (
        "extraction_record",
        "extraction_candidate",
        "extraction_candidate_review",
        "source_classification_elevation",
        "unresolved_identity",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS {table_name}_forbid_mutation ON {table_name};")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_source_supersedes_boundary', 'source', type_='foreignkey')
    op.drop_constraint('uq_source_system_external_ref_hash_boundary', 'source', type_='unique')
    op.drop_column('source', 'supersedes_source_id')
    op.drop_column('source', 'content_location')
    op.drop_column('source', 'content_hash')
    op.drop_table('extraction_candidate_review')
    op.drop_table('unresolved_identity')
    op.drop_table('extraction_candidate')
    op.drop_table('source_classification_elevation')
    op.drop_table('extraction_record')
    op.drop_table('ingestion_run')
    op.drop_table('ingestion_cursor')
    # ### end Alembic commands ###
