"""artifact_backup_run

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-21 17:17:49.745452

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: str | Sequence[str] | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_backup_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trust_boundary', sa.Enum('PERSONAL', 'BRAINSTORM', 'SHARED', name='artifact_backup_run_trust_boundary', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'SUCCEEDED', 'FAILED', name='artifact_backup_run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('artifacts_checked', sa.Integer(), nullable=True),
    sa.Column('artifacts_backed_up', sa.Integer(), nullable=True),
    sa.Column('artifacts_already_protected', sa.Integer(), nullable=True),
    sa.Column('artifacts_repaired', sa.Integer(), nullable=True),
    sa.Column('artifacts_failed', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # D031A: artifact_backup_run is a deliberate mutable exception, like
    # ingestion_cursor/ingestion_run (D030) - pure operational bookkeeping,
    # never authoritative for backup protection status - no append-only
    # trigger is added.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifact_backup_run')
    # ### end Alembic commands ###
